# Uncomment the following lines to enable the Redox RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
# Unlock ZMK Studio automatically without needing a key shortcut
CONFIG_ZMK_STUDIO_LOCKING=n
